name: Health Alchemist
favicon: null
layout_spectrum: 0.73327
typography_spectrum: 0.37732
title: 'The Health Alchemist '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080808'
    - '#5da2e7'
    - '#d6c6ab'
    - '#8b1f3f'
    - '#a46842'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.6875
  rhythmicContrast: 0.6574571302626282
purpose: []
